### ISSUE TITLE
New Requirement : Data Fetch Function in MLAGSQL

### ISSUE THREAD

**Issue by srixivas** [ndprasad09/MLAGDiag#3]
Th MLAGSQL file is loaded with functions to create, delete and insert into different tables with precondition checks which is perfect.
Will we be needing the Data Fetching Functions ? or just use the handle "c.execute"  to perform SELECT operations which comparing the data.
Views on this ?

**Comment by senthilksk78** [comment]
It is much better to create our own specific functions using c to do that.

**Comment by srixivas** [comment]
Done. Used the global cursor object to fetch the data
